on:
  push:

jobs:
  garden:
    env:
      key1: value1
    runs-on: ubuntu-22.04
    steps:
    -
      env:
        key2: value2
      run: |
        cat << "EOF"
        ${{ toJSON(env) }}
        EOF
